version: "3.8"

services:
  # SERVICE DASH
  dash:
    build: 
    # ./app
      context: .
    volumes: 
      - ./app:/app
    tty: true
    ports:
      # HTTP
      - target: 8050
        published: 8050
        protocol: tcp
